# Generated by Django 3.2.12 on 2022-03-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='files/')),
                ('headers_configuration', models.JSONField()),
                ('status', models.CharField(choices=[('HOLD', 'On Hold'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('TERMINATED', 'Terminated')], default='HOLD', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Import',
                'verbose_name_plural': 'Files Import',
            },
        ),
    ]
