# Generated by Django 3.2.12 on 2022-03-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20220327_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileimporterrors',
            name='error',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='fileimporterrors',
            name='record',
            field=models.TextField(),
        ),
    ]
